# -*- coding: utf-8 -*-
"""PREPROCESSING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZNKB5pmd0uj2jEaZeHcpakLYVVWQwzPx

# ***-DATASET PREPARATION-***
"""

# ENVIRONMENT SETUP
import os
import zipfile
from itertools import islice
from collections import Counter, defaultdict
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
from google.colab import drive, data_table

print("LIBRARY VERSIONS")
print("=" * 70)
print(f"NumPy version\t: {np.__version__}\nPandas version\t: {pd.__version__}\nNetworkX ver.\t: {nx.__version__}\nMatplotlib ver.\t: {plt.matplotlib.__version__}\nSeaborn ver.\t: {sns.__version__}")

SHARED_FOLDER_NAME = "GOOGLE-COLAB-AJS"
DRIVE_DIR = f"/content/drive/MyDrive/{SHARED_FOLDER_NAME}"
WORK_DIR = "/content/amazon_work"

os.makedirs(WORK_DIR, exist_ok=True)

# Mount Google Drive
drive.mount('/content/drive')

# Define file paths
META_ZIP_PATH = os.path.join(DRIVE_DIR, "amazon-meta.txt.zip")
GRAPH_ZIP_PATH = os.path.join(DRIVE_DIR, "amazon0302.txt.zip")

# Extract ZIP files to working directory
print("EXTRACTING FILES")
print("=" * 70)
with zipfile.ZipFile(META_ZIP_PATH, 'r') as z:
    z.extractall(WORK_DIR)
    print(f"✓ Extracted: {META_ZIP_PATH}")

with zipfile.ZipFile(GRAPH_ZIP_PATH, 'r') as z:
    z.extractall(WORK_DIR)
    print(f"✓ Extracted: {GRAPH_ZIP_PATH}")

META_PATH = os.path.join(WORK_DIR, "amazon-meta.txt")
GRAPH_PATH = os.path.join(WORK_DIR, "amazon0302.txt")

print("\nHEAD (10 lines): amazon-meta.txt")
print("=" * 70)
with open(META_PATH, "r", encoding="latin-1") as f:
    for line in islice(f, 10):
        print(line.rstrip("\n"))

print("\nHEAD (10 lines): amazon0302.txt")
print("=" * 70)
with open(GRAPH_PATH, "r", encoding="latin-1") as f:
    for line in islice(f, 10):
        print(line.rstrip("\n"))
print()



"""# ***-PREPROCESSING-***

## **Data Integration**

### *Meta Data Parsing*
"""

product_meta = {}

with open(META_PATH, "r", encoding="latin-1") as f:
    current = {}
    cat_lines_remaining = 0

    def finalize_current(cur):
        if not cur or "Id" not in cur:
            return
        pid = cur["Id"]
        product_meta[pid] = {
            "title": cur.get("title", "").strip(),
            "group": cur.get("group", "").strip(),
            "category_lines": cur.get("category_lines", []),
        }

    for raw in f:
        line = raw.rstrip("\n")

        if not line.strip():
            finalize_current(current)
            current = {}
            cat_lines_remaining = 0
            continue

        striped = line.strip()

        if striped.startswith("Id:"):
            try:
                current["Id"] = int(striped.split("Id:")[1].strip())
            except ValueError:
                pass
        elif striped.startswith("title:"):
            current["title"] = striped.split("title:")[1].strip()
        elif striped.startswith("group:"):
            current["group"] = striped.split("group:")[1].strip()
        elif striped.startswith("categories:"):
            parts = striped.split()
            if len(parts) >= 2:
                try:
                    cat_lines_remaining = int(parts[1])
                except ValueError:
                    cat_lines_remaining = 0
            current.setdefault("category_lines", [])
        elif striped.startswith("|") and cat_lines_remaining > 0:
            current.setdefault("category_lines", []).append(line)
            cat_lines_remaining -= 1

    finalize_current(current)

print("META DATA PARSING RESULTS")
print("=" * 70)
print(f"Total products parsed: {len(product_meta)}")

group_counts = Counter(info["group"] for info in product_meta.values())
print("\nProduct group distribution:")
for group, count in group_counts.most_common():
    print(f"  {group:20s}: {count:,}")

df_meta_sample = pd.DataFrame([
    {"ID": pid, "title": info["title"], "group": info["group"],
     "categories_count": len(info["category_lines"])}
    for pid, info in list(product_meta.items())[:10]
])

print("\nSample data (first 10 products):")
print(df_meta_sample.to_string(index=False))
print()

"""### *DVD Subset Extraction*"""

# Backup: full product metadata
product_meta_full = product_meta.copy()

dvd_ids = {pid for pid, info in product_meta.items() if info.get("group") == "DVD"}

edges_dvd = []
nodes_with_edges = set()

with open(GRAPH_PATH, "r") as f:
    for raw in f:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        try:
            u, v = int(parts[0]), int(parts[1])
        except ValueError:
            continue

        if (u in dvd_ids) and (v in dvd_ids):
            edges_dvd.append((u, v))
            nodes_with_edges.add(u)
            nodes_with_edges.add(v)

print("DVD SUBSET EXTRACTION RESULTS")
print("=" * 70)
print("Before filtering:")
print(f"  Total products: {len(product_meta_full):,}")

print("\nAfter DVD filtering:")
print(f"  Total DVD products: {len(dvd_ids):,}")
print(f"  Total DVD-to-DVD edges: {len(edges_dvd):,}")
print(f"  DVD nodes with edges (degree ≥ 1): {len(nodes_with_edges):,}")
print(f"  Isolated DVDs/Not DVD-to-DVD Relationship: {len(dvd_ids - nodes_with_edges):,}")
print(f"  Reduction: {len(product_meta_full) - len(dvd_ids):,} products removed")

df_dvd = pd.DataFrame([
    {
        "ID": u,
        "title": product_meta[u]["title"],
        "co_purchases": v,
        "title_co_purchases": product_meta[v]["title"],
    }
    for u, v in edges_dvd[:10]
])

print("\nSample DVD edges (first 10):")
print(df_dvd.to_string(index=False))

print(f"\nBackup: Full product metadata saved as 'product_meta_full'")
print()

"""## **Genre Detection Algorithm**"""

EXCLUDED_IF_OTHERS = {"Art House & International", "Television"}
TITLE_FORCE_MAP = [
    ("red shoe diaries", "Drama"),
    ("freefall 3050", "Action & Adventure"),
    ("tempest 3000", "Action & Adventure"),
    ("i love toy trains", "Kids & Family"),
    ("dorf goes", "Comedy"),
    ("little rascals", "Comedy"),
    ("the shooting", "Action & Adventure"),
]
TITLE_KEYWORDS = {
    "Anime & Manga": ["yu-gi-oh", "yu gi oh", "yugioh", "yu yu hakusho", "dna2", "dna 2", "lupin the 3rd", "lupin iii"],
    "Adult": ["playboy", "sex", "erotic", "porn", "lust", "vinyl dolls", "penthouse", "sensual", "orgasm", "nude", "showgirl", "hyper police"],
}
SPECIAL_MAP = {"Westerns": "Classics", "Cult Movies": "Horror"}

def _clean_segments(cat_line):
    segs = [s for s in cat_line.strip().split("|") if s]
    return [s.rsplit("[", 1)[0].strip() for s in segs]

def _paths_from_category_lines(category_lines):
    paths = []
    for raw in (category_lines or []):
        if not raw.strip().startswith("|"):
            continue
        names = _clean_segments(raw)
        if "Genres" in names:
            paths.append(" > ".join(names))
    return paths

def infer_genre(category_lines, title):
    counter = Counter()
    for raw in (category_lines or []):
        if not raw.strip().startswith("|"):
            continue
        names = _clean_segments(raw)
        if "Genres" not in names:
            continue
        idx = names.index("Genres")
        if idx + 1 >= len(names):
            continue

        first = names[idx + 1]
        cand = names[idx + 2] if (first == "Special Interests" and idx + 2 < len(names)) else first
        cand = SPECIAL_MAP.get(cand, cand)

        w = 2 if "General" in names[idx + 1:] else 1
        counter[cand] += w

    if len(counter) > 1:
        for ex in list(EXCLUDED_IF_OTHERS):
            if ex in counter and len(counter) > 1:
                del counter[ex]

    if counter:
        return counter.most_common(1)[0][0]

    t = (title or "").lower()
    for key, g in TITLE_FORCE_MAP:
        if key in t:
            return g
    for g, kws in TITLE_KEYWORDS.items():
        if any(k in t for k in kws):
            return g
    return "UNCATEGORIZED"

print("GENRE DETECTION RULES SUMMARY")
print("=" * 70)
print("Primary: token setelah 'Genres' pada path categories; 'Special Interests' → ambil sub-genre setelahnya")
print("Weighting: path mengandung 'General' diberi bobot lebih")
print("If alternatives exist: buang 'Art House & International' dan 'Television'")
print("Mapping khusus: Westerns→Classic; Cult Movies→Horror")
print("Fallback title-based: Adult/Anime & Manga + beberapa judul spesifik\n")

print("GENRE DISTRIBUTION (BEFORE)")
print("=" * 70)
print(f"UNCATEGORIZED: {len(dvd_ids):,}\n")

genres = {pid: infer_genre(product_meta[pid].get("category_lines", []), product_meta[pid].get("title", "")) for pid in dvd_ids}

rows = []
for u, v in edges_dvd:
    rows.append({
        "ID": u,
        "title": product_meta[u].get("title", "").strip(),
        "genre": genres.get(u, "UNCATEGORIZED"),
        "ID_cp": v,
        "title_cp": product_meta[v].get("title", "").strip(),
        "genre_cp": genres.get(v, "UNCATEGORIZED"),
    })

df = pd.DataFrame(rows)

print("SAMPLE (first 5)")
print("=" * 70)
print(df.head(5).to_string(index=False))
print()

out_path = f"{WORK_DIR}/amazon0302_DVD_genre.csv" if "WORK_DIR" in globals() else "amazon0302_DVD_with_genres.csv"
df.to_csv(out_path, index=False)
print(f"File saved: {out_path}")

data_table.DataTable(df, include_index=False, num_rows_per_page=20)

def print_genre_distribution(df, col_from="genre", col_to="genre_cp", title="GENRE DISTRIBUTION (AFTER)"):
    print(title)
    print("=" * 70)

    vc_from = df[col_from].value_counts()
    vc_to = df[col_to].value_counts()

    all_genres = sorted(set(vc_from.index) | set(vc_to.index))

    unc = int(vc_from.get("UNCATEGORIZED", 0))
    print(f"UNCATEGORIZED: {unc:,}\n")

    total_all = int(vc_from.sum() + vc_to.sum())

    print("genre")
    for g in all_genres:
        from_cnt = int(vc_from.get(g, 0))
        to_cnt = int(vc_to.get(g, 0))
        total = from_cnt + to_cnt
        if total > 0:
            pct = (total / total_all * 100) if total_all else 0.0
            print(f"{g:30s} {total:5d} ({from_cnt}+{to_cnt})\t\t{pct:6.2f}%")

    print()

print_genre_distribution(
    df,
    col_from="genre",
    col_to="genre_cp",
    title="GENRE DISTRIBUTION (AFTER) - FROM (source DVDs)"
)

"""## **Graph Network Reduction**

### *Genre Optimization*
"""

print("GENRE REDUCTION RESULTS")
print("=" * 70)

df_before = df.copy()

nodes_before = pd.Index(df_before["ID"]).append(pd.Index(df_before["ID_cp"])).unique()
edges_before = len(df_before)

unc_before_from = int((df_before["genre"] == "UNCATEGORIZED").sum())
unc_before_to = int((df_before["genre_cp"] == "UNCATEGORIZED").sum())

print("Before reduction:")
print(f"  Nodes: {len(nodes_before):,}")
print(f"  Edges: {edges_before:,}")
print(f"  UNCATEGORIZED (FROM): {unc_before_from:,}")
print(f"  UNCATEGORIZED (TO):   {unc_before_to:,}\n")

genre_merge = {
    "Action": "Action & Adventure",
    "Anime & Manga": "Animation",
    "Art & Artists": "Art & International",
    "Art House & International": "Art & International",
    "Fitness & Yoga": "Sports",
    "Outdoor Recreation": "Nature & Wildlife",
    "Outdorr Recreation": "Nature & Wildlife",
}

df_work = df_before.copy()
df_work["genre"] = df_work["genre"].replace(genre_merge)
df_work["genre_cp"] = df_work["genre_cp"].replace(genre_merge)

df_work = df_work[
    (df_work["genre"] != "UNCATEGORIZED") &
    (df_work["genre_cp"] != "UNCATEGORIZED")
].copy()

nodes_after = pd.Index(df_work["ID"]).append(pd.Index(df_work["ID_cp"])).unique()
edges_after = len(df_work)

print("After reduction:")
print(f"  Nodes: {len(nodes_after):,}")
print(f"  Edges: {edges_after:,}")
print(f"  Reduction: {len(nodes_before) - len(nodes_after):,} nodes, {edges_before - edges_after:,} edges\n")

print("Sample (first 5):")
print(df_work.head(5).to_string(index=False))
print()

df_dvd_genre_reduction = df_work
print("Backup note: result saved as 'df_dvd_genre_reduction'\n")

"""### *Low-Degree Node Removal*"""

DEGREE_THRESHOLD = 3

print(f"LOW-DEGREE NODE REMOVAL RESULTS (total degree < {DEGREE_THRESHOLD})")
print("=" * 70)

df_before = df_dvd_genre_reduction.copy()

G_tmp = nx.DiGraph()
G_tmp.add_edges_from(
    df_before[["ID", "ID_cp"]].itertuples(index=False, name=None)
)

total_deg = dict(G_tmp.degree())
low_nodes = {n for n, d in total_deg.items() if d < DEGREE_THRESHOLD}

nodes_before = pd.Index(df_before["ID"]).append(
    pd.Index(df_before["ID_cp"])
).unique()
edges_before = len(df_before)

print("Before removal:")
print(f"  Nodes: {len(nodes_before):,}")
print(f"  Edges: {edges_before:,}")
print(f"  Nodes with total degree < {DEGREE_THRESHOLD}: {len(low_nodes):,}\n")

df_work = df_before[
    (~df_before["ID"].isin(low_nodes)) &
    (~df_before["ID_cp"].isin(low_nodes))
].copy()

nodes_after = pd.Index(df_work["ID"]).append(
    pd.Index(df_work["ID_cp"])
).unique()
edges_after = len(df_work)

print("After removal:")
print(f"  Nodes: {len(nodes_after):,}")
print(f"  Edges: {edges_after:,}")
print(f"  Reduction: {len(nodes_before) - len(nodes_after):,} nodes, {edges_before - edges_after:,} edges\n")

print("Sample (first 5):")
print(df_work.head(5).to_string(index=False))
print()

df_final = df_work
print("Note: df_final updated (overwritten) with low-degree filtered data\n")

out_csv = f"{WORK_DIR}/amazon0302_DVD_optimized.csv" if "WORK_DIR" in globals() else "amazon0302_DVD_optimized.csv"
df_final.to_csv(out_csv, index=False)
print(f"File saved: {out_csv}\n")

data_table.DataTable(df_final, include_index=False, num_rows_per_page=20)

def build_directed_graph(df):
    G = nx.DiGraph()
    G.add_edges_from(df[["ID", "ID_cp"]].itertuples(index=False, name=None))

    genre_map = pd.concat([
        df[["ID", "genre"]].rename(columns={"ID": "node", "genre": "genre"}),
        df[["ID_cp", "genre_cp"]].rename(columns={"ID_cp": "node", "genre_cp": "genre"})
    ]).drop_duplicates("node").set_index("node")["genre"].to_dict()

    nx.set_node_attributes(G, genre_map, "genre")
    return G

G = build_directed_graph(df_final)

edge_txt = f"{WORK_DIR}/amazon0302_DVD_optimized_edgelist.txt" if "WORK_DIR" in globals() else "amazon0302_DVD_optimized_edgelist.txt"
df_final[["ID", "ID_cp"]].to_csv(edge_txt, sep=" ", header=False, index=False)
print(f"Edge-list saved: {edge_txt}\n")

print("Head (first 5 lines) of edgelist:")
with open(edge_txt, "r") as f:
    for _ in range(5):
        print(f.readline().rstrip("\n"))
print()